name: go_build

on:
  release:
    types: [created]

jobs:
  build:
    name: build_to_release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel (TODO): linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux]
        goarch: [amd64]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Read version from release.json
        uses: notiz-dev/github-action-json-property@release
        id: edithctl_version
        with:
          path: "release.json"
          prop_path: "version"

      - name: Read go_version from release.json
        uses: notiz-dev/github-action-json-property@release
        id: go_version
        with:
          path: "release.json"
          prop_path: "go_version"

      - name: Build edith binary
        uses: wangyoucao577/go-release-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://dl.google.com/go/go${{ steps.go_version.outputs.prop }}.linux-amd64.tar.gz"
          binary_name: "edith"
          ldflags: "-X 'github.com/theycallmeloki/edith-cli/cmd/edith.version=${{ steps.edithctl_version.outputs.prop }}'"
